import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Barre from '@/components/barre'
import BackImageHome from '@/components/backImageHome'
import Card from '@/components/card'







export default function Home() {
  return (
    <>
      <Head>
        <title>Tv Infinity</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
       
      </Head>

     
      <section>
        <div className={`row align-items-center ${styles.imageback}`}>
          <BackImageHome/>
        </div>
      </section>

      <section>
        <Barre/>
      </section>

      <section className={`mt-5   ${styles.section3}`}>

        <h1 className='text-center mt-5 mb-5'>THANK YOU FOR CHOOSING INFINITY IPTV</h1>
        <div className='container-fluid d-block  d-xs-block  d-md-block d-sm-block d-lg-flex justify-content-lg-evenly flex-lg-wrap'>

            <div className={` mb-5 ${styles.divcard}`} mb-3 ><Card  mois = '3' price='35'/></div>
            <div className={` mb-5 ${styles.divcard}`}><Card mois = '3' price='35'/></div>
            <div className={` mb-5 ${styles.divcard}`}><Card mois = '3' price='35'/></div>
                      
        </div>
        
      </section>

      <section>
        <h1>section 4</h1>
      </section>


         
    </>
  )
}
